- hosts: webserver
  tasks:
  - name: Docker Installing
    command: "yum install docker-ce --nobest -y"
    when: "'docker-ce' not in ansible_facts.package"


  - name: "Pull tomcat image"
    docker_image:
      name: kwabena81/tomcat-image
      source: pull

